In [4]:
import pandas as pd
import numpy as np
import os
from sqlalchemy import create_engine, text
import warnings
warnings.filterwarnings('ignore')

print("All libraries imported successfully")

All libraries imported successfully

In [5]:
# Use absolute path — works no matter where the notebook is
BASE_DIR = r"C:\Users\Administrator\Desktop\kenya_road_safety_project"
RAW_DATA = os.path.join(BASE_DIR, "data", "raw", "accidents-database-.csv")

# Load the CSV
df = pd.read_csv(RAW_DATA)

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("\nFile loaded successfully!")
df.head(3)

Shape: (1119, 15)
Columns: ['TIME 24 HOURS', 'BASE/SUB BASE', 'COUNTY', 'ROAD', 'PLACE', 'MV INVOLVED', 'BRIEF ACCIDENT DETAILS', 'NAME OF VICTIM', 'GENDER', 'AGE', 'CAUSE CODE', 'VICTIM', 'NO.', 'Date DD/MM/YYYY', 'Unnamed: 14']

File loaded successfully!

,TIME 24 HOURS,BASE/SUB BASE,COUNTY,ROAD,PLACE,MV INVOLVED,BRIEF ACCIDENT DETAILS,NAME OF VICTIM,GENDER,AGE,CAUSE CODE,VICTIM,NO.,Date DD/MM/YYYY,Unnamed: 14
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,UNKNOWN,M,26,7,M/CYCLIST,1,06/25/16,so MM/DD/YYYY is the solution :)
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,UNKNOWN,M,28,25,M/CYCLIST,1,06/25/16,NaN
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,UNKNOWN,M,A & J,98,M/CYCLIST,1,06/25/16,NaN

In [6]:
# Check data types and missing values
print("DATA TYPES:")
print(df.dtypes)
print("\nMISSING VALUES:")
print(df.isnull().sum())
print("\nBASIC STATS:")
df.describe(include='all')

DATA TYPES:
TIME 24 HOURS             object
BASE/SUB BASE             object
COUNTY                    object
ROAD                      object
PLACE                     object
MV INVOLVED               object
BRIEF ACCIDENT DETAILS    object
NAME OF VICTIM            object
GENDER                    object
AGE                       object
CAUSE CODE                object
VICTIM                    object
NO.                       object
Date DD/MM/YYYY           object
Unnamed: 14               object
dtype: object

MISSING VALUES:
TIME 24 HOURS                5
BASE/SUB BASE                2
COUNTY                       3
ROAD                         3
PLACE                        6
MV INVOLVED                  0
BRIEF ACCIDENT DETAILS       1
NAME OF VICTIM               1
GENDER                       0
AGE                          1
CAUSE CODE                  28
VICTIM                       0
NO.                          4
Date DD/MM/YYYY              0
Unnamed: 14               1117
dtype: int64

BASIC STATS:

,TIME 24 HOURS,BASE/SUB BASE,COUNTY,ROAD,PLACE,MV INVOLVED,BRIEF ACCIDENT DETAILS,NAME OF VICTIM,GENDER,AGE,CAUSE CODE,VICTIM,NO.,Date DD/MM/YYYY,Unnamed: 14
count,1114,1117,1116,1116,1113,1119,1118,1118,1119,1118,1091,1119,1115,1119,2
unique,199,213,58,715,1023,971,469,369,20,106,73,53,11,168,2
top,2030,NAKURU,NAIROBI,NAIROBI MOMBASA,NEAR KANGEMI STAGE,UNKNOWN,THE VEHICLE KNOCKED DOWN THE VICTIM,UNKNOWN,M,A,98,PEDESTRIAN,1,8/27/2017,so MM/DD/YYYY is the solution :)
freq,44,31,183,23,3,54,219,742,941,545,224,448,1020,22,1

In [8]:
from sqlalchemy import create_engine, text

# @ in password must be written as %40
engine = create_engine(
    'postgresql://postgres:Agie%402015@localhost:5432/kenya_road_safety'
)

# Test connection
with engine.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print("Connected successfully!")
    print("PostgreSQL version:", result.fetchone()[0])

Connected successfully!
PostgreSQL version: PostgreSQL 17.4 on x86_64-windows, compiled by msvc-19.42.34436, 64-bit

In [9]:
# Load the entire raw CSV as-is into a staging table first
# This is a safe way to get data in before cleaning

df.to_sql(
    'accidents_raw',        # staging table name
    engine,
    if_exists='replace',    # replace if already exists
    index=False,
    chunksize=500           # load in chunks for safety
)

# Verify it loaded
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM accidents_raw"))
    print(f"Records loaded: {count.fetchone()[0]}")

Records loaded: 1119

In [10]:
# Read back from database to confirm
df_check = pd.read_sql('SELECT * FROM accidents_raw LIMIT 5', engine)
print("Data in PostgreSQL:")
df_check

Data in PostgreSQL:

,TIME 24 HOURS,BASE/SUB BASE,COUNTY,ROAD,PLACE,MV INVOLVED,BRIEF ACCIDENT DETAILS,NAME OF VICTIM,GENDER,AGE,CAUSE CODE,VICTIM,NO.,Date DD/MM/YYYY,Unnamed: 14
0,630,KITUI,MAKUENI,KITUI-ITHOKWE,KITUI SCHOOL,KAV 479E & KMCZ 732L SKYGO,HEAD ON COLLISION,UNKNOWN,M,26,7,M/CYCLIST,1,06/25/16,so MM/DD/YYYY is the solution :)
1,830,VOI,TAITA TAVETA,MOMBASA-NAIROBI,IKANGA,KCC 763/ZF 0097 MAKE RENAULT TRUCK & KMDN 759R...,HEAD ON COLLISION,UNKNOWN,M,28,25,M/CYCLIST,1,06/25/16,None
2,1330,MARIAKANI,KILIFI,MOMBASA-NAIROBI,KATOLANI,KMDK 017U HAOJIN,THE UNKNOWN M/V HIT THE MOTOR CYCLE,UNKNOWN,M,A & J,98,M/CYCLIST,1,06/25/16,None
3,2100,ONGATA RONGAI,NAKURU,NAKURU-NAIROBI,MAASAI LODGE,KAL 900K RANGE ROVER,THE VEHICLE KNOCKED DOWN A PEDESTRIAN WHO WAS ...,UNKNOWN,M,65,29,PEDESTRIAN,1,06/25/16,None
4,1900,MATUU,MACHAKOS,MATUU-MWINGI,KIVANDINI,KAQ 865Z TOYOTA COROLLA,THE VEHICLE OVERTOOK A M/CYCLE AND LOST CONTRO...,UNKNOWN,M,A,10,PASSENGER,1,06/25/16,None